accounts/urls.py
from django.urls import path
from .views import signin, signout

app_name = 'accounts'


urlpatterns = [
    path('', signin, name='signin'),
    path('signout/', signout, name='signout'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('farm/', include('farms.urls')),
    path('', include('accounts.urls')),
]

if settings.DEBUG:
    urlpatterns +=  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns +=  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

farms/urls.py
from django.urls import path

from farms.models import Losses
from .views import (
            farms, create_farm, edit_farm, profilechicken,
            create_profilechicken,edit_profilechicken,vaccinations,
            create_vaccination,edit_vaccination,manufacturing_farm,create_manufacturing,
            edit_manufacturing,farm, create_losse, edit_losse, losse, losses,
            incaomes, create_incaome, edit_incaome, functions, edit_function, 
            create_function, create_manage, edit_manage, schedules, create_schedule,
            edit_schedule, make_bery, create_make_bery, edit_make_bery, medicians, 
            create_medician, edit_medician, add_image_to_medician, all_image_medician,
            remove_image_medician, labratores, create_labratore, edit_labratore,
            remove_image_labratore, add_image_to_labratore, all_image_labratore,
        )

app_name = 'farms'

urlpatterns = [
    path('', farms, name='farms'),
    path('<int:pk>/', farm, name='farm'),
    path('create/farm/', create_farm, name='create_farm'),
    path('edit/farm/<int:pk>/', edit_farm, name='edit_farm'),
    path('profilechicken/<int:pk>/', profilechicken, name='profilechicken'),
    path('create/profilechicken/<int:pk>/', create_profilechicken, name='create_profilechicken'),
    path('edit/profilechicken/<int:pk>/', edit_profilechicken, name='edit_profilechicken'),
    path('vaccinations/<int:pk>/', vaccinations, name='vaccinations'),
    path('create/vaccination/<int:pk>/', create_vaccination, name='create_vaccination'),
    path('edit/vaccination/<int:pk>/', edit_vaccination, name='edit_vaccination'),
    path('manufacturing/all/<int:pk>/', manufacturing_farm, name='manufacturing_farm'),
    path('create/manufacturing/<int:pk>/', create_manufacturing, name='create_manufacturing'),
    path('edit/manufacturing/<int:pk>/', edit_manufacturing, name='edit_manufacturing'),
    path('edit/losse/<int:pk>/', edit_losse, name='edit_losse'),
    path('create/losse/<int:pk>/', create_losse, name='create_losse'),
    path('losse/<int:pk>/', losse, name='losse'),
    path('losses/<int:pk>/', losses, name='losses'),
    path('edit/incaome/<int:pk>/', edit_incaome, name='edit_incaome'),
    path('create/incaome/<int:pk>/', create_incaome, name='create_incaome'),
    path('incaomes/<int:pk>/', incaomes, name='incaomes'),
    path('edit/function/<int:pk>/', edit_function, name='edit_function'),
    path('create/function/<int:pk>/', create_function, name='create_function'),
    path('functions/<int:pk>/', functions, name='functions'),
    path('create/manage/<int:pk>/', create_manage, name='create_manage'),
    path('edit/manage/<int:pk>/', edit_manage, name='edit_manage'),
    path('edit/schedule/<int:pk>/', edit_schedule, name='edit_schedule'),
    path('create/schedule/<int:pk>/', create_schedule, name='create_schedule'),
    path('schedule/<int:pk>/', schedules, name='schedules'),
    path('make_bery/<int:pk>/', make_bery, name='make_bery'),
    path('create/make_bery/<int:pk>/', create_make_bery, name='create_make_bery'),
    path('edit/make_bery/<int:pk>/', edit_make_bery, name='edit_make_bery'),
    path('medicians/<int:pk>/', medicians, name='medicians'),
    path('create/medician/<int:pk>/', create_medician, name='create_medician'),
    path('edit/medician/<int:pk>/', edit_medician, name='edit_medician'),
    path('add/image_to_medician/<int:pk>/', add_image_to_medician, name='add_image_to_medician'),
    path('all/image_medician/<int:pk>/', all_image_medician, name='all_image_medician'),
    path('remove/image_medician/<int:pk>/', remove_image_medician, name='remove_image_medician'),
    path('labratores/<int:pk>/', labratores, name='labratores'),
    path('create/labratore/<int:pk>/', create_labratore, name='create_labratore'),
    path('edit/labratore/<int:pk>/', edit_labratore, name='edit_labratore'),
    path('add/image_to_labratore/<int:pk>/', add_image_to_labratore, name='add_image_to_labratore'),
    path('all/image_labratore/<int:pk>/', all_image_labratore, name='all_image_labratore'),
    path('remove/image_labratore/<int:pk>/', remove_image_labratore, name='remove_image_labratore'),
]

farms/views.py
from django.contrib import messages
from django.core.paginator import Paginator
from django.forms.models import modelformset_factory

from django.shortcuts import get_object_or_404, redirect, render
from .models import (
            FarmManage, Farms, Function, ImageLabratore, ImageMedician, Incaome, Losses, MakBery, ProfileChickens, 
            Schedule, Vaccination, Manufacturing, Medician, labratore
        )
from .forms import (
            FarmForm, FunctionForm, ImageLabratoreForm, ImageMedicianForm, IncaomForm, LabratoreForm, LossesForm, 
            ManufacturingForm, ProfilechickenForm, ScheduleForm, MakeBeryForm, 
            VaccinationForm,MedicianForm, ManagerForm, ImageMedician
        )
from django.db.models import Sum
# Create your views here.
from django.db import connection, reset_queries
import time

def debugger(func):
    def wrapper(*args, **kwargs):
        reset_queries()
        st=time.time()
        value = func(*args, **kwargs)
        et=time.time()

        queries = len(connection.queries)
        print(f"'--------------------------------------',{queries} ,' ----time:',{et-st}")
        return value
    return wrapper


def farms(request):
    farmses = Farms.objects.only('pk','image','name_type','active','date_start').order_by('-active','-id')
    paginator = Paginator(farmses, 24) 
    page = request.GET.get('page')
    farms = paginator.get_page(page)
    context = {
        'farms':farms
    }

    return render(request, 'farms.html', context)


def farm(request, pk):
    farm = get_object_or_404(Farms, pk=pk)
    manage = farm.farms_farmmanage.all()

    context = {
        'farm':farm,
        'manage':manage
    }
    
    return render(request, 'farm.html', context)


def create_farm(request):
    if request.method == 'POST':
        form = FarmForm(request.POST, request.FILES)
        if form.is_valid():
            cd = form.cleaned_data
            obj = form.save()
            return redirect('farms:farm', obj.pk)
        else:
            form = FarmForm(request.POST, request.FILES)
            context = {
                'form':form
            }
            return render(request, 'create.html', context)
    else:
        form = FarmForm()
        return render(request, 'create.html',{'form':form})


def edit_farm(request, pk):
    farm = get_object_or_404(Farms, pk=pk)

    if not farm.active:
        messages.warning(request, 'این مزرعه فعال نمی باشد', 'warning')
        return redirect('farms:farm', pk)

    if request.method == 'POST':
        form = FarmForm(request.POST, request.FILES, instance=farm)
        if form.is_valid():
            cd = form.cleaned_data
            obj = form.save()
            return redirect('farms:farm', obj.pk)
        else:
            form = FarmForm(request.POST, request.FILES)
            context = {
                'form':form
            }
            return render(request, 'create.html', context)
    else:
        form = FarmForm(instance=farm)
        return render(request, 'create.html',{'form':form})


def profilechicken(request, pk):
    profile = ProfileChickens.objects.select_related('which_farm').filter(which_farm__pk=pk).first()

    context = {
        'profile':profile
    }

    return render(request, 'medicians.html', {'profile':profile})


def create_profilechicken(request, pk):
    try:
        ProfileChickens.objects.get(which_farm__pk=pk)
        messages.error(request, 'این مزرعه زیر کشت می باشد', 'error')
        return redirect('farms:farm', pk)

    except ProfileChickens.DoesNotExist:
        farm = get_object_or_404(Farms, pk=pk)
    
        if not farm.active:
            messages.warning(request, 'این مزرعه فعال نمی باشد', 'warning')
            return redirect('farms:farm', farm.pk)

        if request.method == 'POST':
            form = ProfilechickenForm(request.POST)
            if form.is_valid():
                cd = form.cleaned_data
                obj = form.save()
                return redirect('farms:profilechicken', obj.pk)
            else:
                form = ProfilechickenForm(request.POST)
                context = {
                    'form':form
                }
                return render(request, 'create.html', context)
        else:

            data = {'which_farm':farm}
            form = ProfilechickenForm(initial=data)
            return render(request, 'create.html',{'form':form})
    

def edit_profilechicken(request, pk):
    farm = get_object_or_404(ProfileChickens, pk=pk)
    
    if not farm.which_farm.active:
        messages.warning(request, 'این مزرعه فعال نمی باشد', 'warning')
        return redirect('farms:profilechicken', farm.which_farm.pk)

    if request.method == 'POST':
        form = ProfilechickenForm(request.POST, instance=obj)
        if form.is_valid():
            cd = form.cleaned_data
            obj = form.save()
            return redirect('farms:profilechicken', obj.pk)
        else:
            form = ProfilechickenForm(request.POST)
            context = {
                'form':form
            }
            return render(request, 'create.html', context)

    else:

        form = ProfilechickenForm(instance=farm)
        return render(request, 'create.html',{'form':form})   


def vaccinations(request, pk):
    queries = Vaccination.objects.select_related('which_farm').filter(which_farm__pk=pk)

    context = {
        'vaccinations':queries
    }

    return render(request, 'medicians.html', context)


def create_vaccination(request, pk):
    obj = get_object_or_404(Farms, pk=pk)

    if not obj.active:
        messages.error(request, 'این مزرعه فعال نمی باشد', 'error')
        return redirect('farms:farm', obj.pk)

    if request.method == 'POST':
        form = VaccinationForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            form.save()
            return redirect('farms:vaccinations', obj.pk)
        else:
            form = VaccinationForm(request.POST)
            context = {
                'form':form
            }
            return render(request, 'create.html', context)
    else:
        data = {'which_farm': obj}
        form = VaccinationForm(initial=data)
        return render(request, 'create.html',{'form':form})

def edit_vaccination(request, pk):

    obj = get_object_or_404(Vaccination, pk=pk)
    if not obj.which_farm.active:
        messages.error(request, 'این مزرعه فعال نمی باشد', 'error')
        return redirect('farms:vaccinations', obj.which_farm.pk)
    
    if request.method == 'POST':
        form = VaccinationForm(request.POST, instance=obj)
        if form.is_valid():
            cd = form.cleaned_data
            obj = form.save()
            return redirect('farms:vaccination', obj.pk)
        else:
            form = VaccinationForm(request.POST)
            context = {
                'form':form
            }
            return render(request, 'create.html', context)

    else:

        form = VaccinationForm(instance=obj)
        return render(request, 'create.html',{'form':form})



def functions(request, pk):
    functions = Function.objects.select_related('which_farm').filter(which_farm__pk=pk)
    context = {
        'functions': functions
    }

    return render(request, 'medicians.html', context)

def create_function(request, pk):
    farm = get_object_or_404(Farms, pk=pk)

    if not farm.active:
        messages.error(request, 'این مزرعه فعال نمی باشد', 'error')
        return redirect('farms:farm', farm.pk)


    if request.method == 'POST':
        form = FunctionForm(request.POST)

        if form.is_valid():
            cd = form.cleaned_data
            form.save()
            return redirect('farms:functions', pk)
        else:
            form = FunctionForm(request.POST)
            return render(request, 'create.html', {'form':form})
    else:
        data = {'which_farm': farm}
        form = FunctionForm(initial=data)
        return render(request, 'create.html', {'form':form})

def edit_function(request, pk):
    farm = get_object_or_404(Function, pk=pk)

    if not farm.active:
        messages.error(request, 'این مزرعه فعال نمی باشد', 'error')
        return redirect('farms:farm', farm.pk)

    if request.method == 'POST':
        form = FunctionForm(request.POST, instance=farm)

        if form.is_valid():
            cd = form.cleaned_data
            obj = form.save()
            pk = obj.which_farm.pk
            return redirect('farms:functions', pk)
        else:
            return render(request, 'create.html', {'form':form})
    else:
        form = FunctionForm(instance=farm)
        return render(request, 'create.html', {'form':form})

def schedules(request, pk):
    schedules = Schedule.objects.select_related('which_farm').filter(which_farm__pk=pk)

    context = {
        'schedules': schedules
    }

    return render(request, 'medicians.html', context)


def create_schedule(request, pk):
    farm = get_object_or_404(Farms, pk=pk)

    if not farm.active:
        messages.error(request, 'این مزرعه فعال نمی باشد', 'error')
        return redirect('farms:farm', farm.pk)

    if request.method == 'POST':
        form = ScheduleForm(request.POST)

        if form.is_valid():
            cd = form.cleaned_data
            form.save()
            return redirect('farms:schedules', farm.pk)
        else:
            form = ScheduleForm(request.POST)
            return render(request, 'create.html', {'form':form})
    else:
        
        data = {'which_farm': farm}
        form = ScheduleForm(initial=data)
        return render(request, 'create.html', {'form':form})

def edit_schedule(request, pk):
    obj = get_object_or_404(Schedule, pk=pk)
    if not obj.active:
        messages.error(request, 'این مزرعه فعال نمی باشد', 'error')
        return redirect('farms:farm', obj.pk)

    if request.method == 'POST':
        form = ScheduleForm(request.POST, instance=obj)

        if form.is_valid():

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible"
        content="IE=edge">
  <meta name="viewport"
        content="width=device-width, initial-scale=1.0">

  <!-- SEO MetaTags -->
  <meta name="robots"
        content="index, follow" />
  <meta name="description"
        content="{% block meta_description %}{% endblock meta_description %}" />
  <meta name="keywords"
        content="{% block meta_keywords %} {% endblock meta_keywords %}" />
	
	
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'fontawesome/css/all.min.css' %}"> <!-- https://fontawesome.com/ -->
    <link href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro&display=swap" rel="stylesheet">
    <!-- https://fonts.google.com/ -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="{% static 'admin/jquery.ui.datepicker.jalali/themes/base/jquery-ui.min.css' %}">
    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon" />
 
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/templatemo-video-catalog.css' %}">
</head>
<!--

TemplateMo 552 Video Catalog

https://templatemo.com/tm-552-video-catalog

-->
<body>
	<div class="tm-page-wrap mx-auto">
		<div class="position-relative">
			<div class="potition-absolute tm-site-header">
				<div class="container-fluid position-relative">
					<div class="row">						
                        <div class="col-7 col-md-4">
                            <a href="{% url 'farms:farms' %}" class=" text-center ">
                                <img class="col-6" src="{% static 'img/logo.png' %}" alt="">
                            </a>
                        </div>
                        <div class="col-5 col-md-8 ml-auto mr-0">
                            <div class="tm-site-nav">
                                <nav class="navbar navbar-expand-lg mr-0 ml-auto" id="tm-main-nav">
                                    <button class="navbar-toggler tm-bg-black py-2 px-3 mr-0 ml-auto collapsed" type="button"
                                        data-toggle="collapse" data-target="#navbar-nav" aria-controls="navbar-nav"
                                        aria-expanded="false" aria-label="Toggle navigation">
                                        <span>
                                            <i class="fas fa-bars tm-menu-closed-icon"></i>
                                            <i class="fas fa-times tm-menu-opened-icon"></i>
                                        </span>
                                    </button>
                                    <div class="collapse navbar-collapse tm-nav" id="navbar-nav">
                                        <ul class="navbar-nav text-uppercase">
                                            <li class="nav-item">
                                                <a class="nav-link tm-nav-link" href="{% url 'farms:farms' %}">مزرعه ها </a>
                                            </li>
                                            <li class="nav-item active">
                                                <a class="nav-link tm-nav-link" href="{% url 'farms:create_farm' %}">ایجاد مزرعه جدید </a>
                                            </li>
                                            <li class="nav-item">
                                                <a class="nav-link tm-nav-link" href="{% url 'accounts:signout' %}">خروج از سایت</a>
                                            </li>
                                        </ul>
                                    </div>
                                </nav>
                            </div>
                        </div>
					</div>
				</div>
			</div>
            <div class="tm-welcome-container tm-fixed-header tm-fixed-header-3">
				<div class="text-center">
					<p class="pt-5 px-3 tm-welcome-text tm-welcome-text-2 mb-1 mt-lg-0 mt-5 text-white mx-auto">
                        {% block one %} {% endblock %}<br>{% block tow %} {% endblock %}
                        

                    </p>                	
				</div>                
            </div>

            <div id="tm-fixed-header-bg"></div> <!-- Header image -->
		</div>
        {% include 'include/msg.html' %}

        {% block body %} {%endblock%}

        {% block footer %} 
        
		<div class="container-fluid tm-content-container mx-auto pt-4">
        </div>

        {%endblock%}

    </div>

    {% block javascript %} 

    {% endblock %}
    <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/parallax.min.js' %}"></script>    
    <script src="{% static 'admin/js/django_jalali.min.js' %}"></script>

</body>
</html>

templates/medicians.html
{% extends 'base.html' %}
{% load static %}
{% load jalali_tags %}

{% block one %} سیستم مدیریت آنلاین {% endblock %}
{% block tow %}  
            <br>صفحه مربوط به مدیریت
            {% if all_medician %} بهداشت 
            {% elif all_labratore %} آزمایشگاه 
            {% elif profile %} محصول کاشت شده
            {% elif vaccinations %} واکسیناسیون
            {% elif schedules %} برنامه نوردهی
            {% elif all_mak_bery %} مک بری کردن 
            {% elif functions %}
            {% endif %} 
{% endblock %}

{% block body %}
		<div class="container-fluid tm-content-container mx-auto pt-4">
			<!-- Subscribe form and footer links -->
            <div class="row pt-3">
            {% if all_medician %}
                {% for mdc in all_medician %}
                    <div class="col-xl-3 col-lg-12 mb-4">
                        <div class="tm-bg-gray p-5">
                            <h3 class="tm-text-primary mb-3">اطلاعات</h3>
                            تاریخ بازدید:
                            <a class="">{{ mdc.date|to_jalali:'%Y/%m/%d' }}</a> <hr> 
                                {% if mdc.is_sickness %}
                                <a class="text-danger">بیماری مشاهده شد</a> <hr>
                                {% else %}
                                <a class="text-success">وضعیت سفید است</a> <hr>
                                {% endif %}
                            <a class="text-info" href="{% url 'farms:add_image_to_medician' mdc.pk %}"> افزودن عکس های بالینی</a> <hr>
                            <a class="text-info" href="{% url 'farms:all_image_medician' mdc.pk%}">مشاهده عکس های بالینی</a> <hr>
                            <a class="text-info" href="{% url 'farms:edit_medician' mdc.pk %}"> 
                                <i class="material-icons" style="font-size:60px;color:aqua;">drive_file_rename_outline</i> ویرایش
                            </a> 
                        </div>
                    </div>
                    <div class="col-xl-4 col-lg-6 col-md-6 col-sm-6 col-12 mb-4">
                        <div class="p-5 tm-bg-gray h-100">
                            <h3 class="tm-text-primary mb-4">مشخصات بیماری</h3>
                            <p>{{ mdc.section_sickness }}</p>
                        </div>                        
                    </div>
                
                    <div class="col-xl-4 col-lg-6 col-md-6 col-sm-6 col-12 mb-4">
                        <div class="p-5 tm-bg-gray h-100">
                            <h3 class="tm-text-primary mb-4">دستورالعمل های درمانی</h3>
                            <p>{{ mdc.treatmentـinstructions }}</p>
                        </div>                        
                    </div>
                {% endfor %}
            {% elif functions %}
                {% for fun in functions %}
                    <div class="col-xl-4 col-lg-12 mb-4">
                        <div class="tm-bg-gray p-5">
                            <h3 class="tm-text-primary mb-3">اطلاعات</h3>
                            تاریخ شروع:
                            <a class="">{{ fun.m2j}}</a> <hr> 
                            ضریب وزن گیری
                            <a>{{ fun.prduction_weight}} </a> <hr>
                            ضریب تولید
                            <a>{{ fun.production_coefficient }} </a> <hr> 
                            {% if fun.which_farm.active %}
                            <a class="text-info" href="{% url 'farms:edit_function' fun.pk %}"> 
                                <i class="material-icons" style="font-size:60px;color:aqua;">drive_file_rename_outline</i> ویرایش
                            </a> 
                            {% endif %}
                        </div>
                    </div> 
                {% endfor %}
            {% elif all_mak_bery %}
                {% for mak in all_mak_bery %}
                    <div class="col-xl-3 col-lg-12 mb-4">
                        <div class="tm-bg-gray p-5">
                            <h3 class="tm-text-primary mb-3">اطلاعات</h3>
                            تاریخ شروع:
                            <a class="">{{ mak.m2j_start}}</a> <hr> 
                            تاریخ پایان:
                            <a class="">{{ mak.m2j_end }}</a> <hr>    
                            {% if mak.which_farm.active %}
                            <a class="text-info" href="{% url 'farms:edit_make_bery' mak.pk %}"> 
                                <i class="material-icons" style="font-size:60px;color:aqua;">drive_file_rename_outline</i> ویرایش
                            </a> 
                            {% endif %}
                        </div>
                    </div>
                    <div class="col-xl-8 col-lg-12  mb-4">
                        <div class="p-5 tm-bg-gray h-100">
                            <h3 class="tm-text-primary mb-4">توضیحات </h3>
                            <p>{{ mak.description }}</p>
                        </div>                        
                    </div>
                {% endfor %}
            {% elif vaccinations %}
                {% for vac in vaccinations %}
                    <div class="col-xl-3 col-lg-12 mb-4">
                        <div class="tm-bg-gray p-5">
                            <h3 class="tm-text-primary mb-3">اطلاعات</h3>
                            تاریخ بازدید:
                            <a class="">{{ vac.date_injection|to_jalali:'%Y/%m/%d' }}</a> <hr> 
                                {% if vac.doing %}
                                <a class="text-success">تزریق شده است</a> <hr>
                                {% else %}
                                <a class="text-warning">تزریق نشده است</a> <hr>
                                {% endif %}
                                <a> سن تجویز: {{ vac.ageـprescription }}</a> <hr>
                                <a> نوع واکسن: {{ vac.typeـvaccine }}</a> <hr>
                            {% if vac.which_farm.active %}
                            <a class="text-info" href="{% url 'farms:edit_vaccination' vac.pk %}"> 
                                <i class="material-icons" style="font-size:60px;color:aqua;">drive_file_rename_outline</i> ویرایش
                            </a> 
                            {% endif %}
                        </div>
                    </div>
                    <div class="col-xl-4 col-lg-6 col-md-6 col-sm-6 col-12 mb-4">
                        <div class="p-5 tm-bg-gray h-100">
                            <h3 class="tm-text-primary mb-4">اطلاعات  ضروری</h3>
                            <p>{{ vac.informationـRurry }}</p>
                        </div>                        
                    </div>
                
                    <div class="col-xl-4 col-lg-6 col-md-6 col-sm-6 col-12 mb-4">
                        <div class="p-5 tm-bg-gray h-100">
                            <h3 class="tm-text-primary mb-4">روش تجویز</h3>
                            <p>{{ vac.prescriptionـmethod }}</p>
                        </div>                        
                    </div>
                {% endfor %}
            {% elif schedules %}
                {% for sch in schedules %}
                    <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12 mb-4">
                        <div class="p-5 tm-bg-gray h-100">
                            <h3 class="tm-text-primary mb-4">اطلاعات  {{ forloop.counter }}</h3>
                            توضیحات
                            <p>{{ sch.description }}</p> <hr>
                            {% if sch.which_farm.active %}
                            <a href="{% url 'farms:edit_schedule' sch.pk %}">
                                <i class="material-icons" style="font-size:60px;color:aqua;">drive_file_rename_outline</i> ویرایش
                            </a>
                            {% endif %}
                        </div>                        
                    </div>
                {% endfor %}
            {% elif all_labratore %}
                {% for lab in all_labratore %}
                    <div class="col-xl-3 col-lg-12 mb-4">
                        <div class="tm-bg-gray p-5">
                            <h3 class="tm-text-primary mb-3">اطلاعات</h3>
                            تاریخ آزمایش:
                            <a class="">{{ lab.date|to_jalali:'%Y/%m/%d' }}</a> <hr> 
                            <a class="text-info" href="{% url 'farms:add_image_to_labratore' lab.pk %}"> افزودن عکس های آزمایشات</a> <hr>
                            <a class="text-info" href="{% url 'farms:all_image_labratore' lab.pk%}">مشاهده عکس های آزمایشات</a> <hr>
                            {% if lab.which_farm.active %}
                            <a class="text-info" href="{% url 'farms:edit_labratore' lab.pk %}"> 
                                <i class="material-icons" style="font-size:60px;color:aqua;">drive_file_rename_outline</i> ویرایش
                            </a>
                            {% endif %}
                        </div>
                    </div>
                    <div class="col-xl-9 col-lg-12 col-md-12 col-sm-12 col-12 mb-4">
                        <div class="p-5 tm-bg-gray h-100">
                            <h3 class="tm-text-primary mb-4">نتایج بررسی آزمایش</h3>
                            <p>{{ lab.descriptor }}</p>
                        </div>                        
                    </div>
                {% endfor %}
            {% elif profile %}
                <div class="col-12 mb-4">
                    <div class="card w-100">
                        <div class="card-body">
                          <h3 class="card-title text-center">اطلاعات محصول</h3>
                          مبدا
                          <p class="card-text">{{ profile.origin }}</p> <hr>
                          تعداد
                          <p class="card-text">{{ profile.number }}</p> <hr>
                          نژاد
                          <p class="card-text">{{ profile.breeds }}</p> <hr>
                          سن ورود به مزرعه
                          <p class="card-text">{{ profile.age_into_farm }}</p> <hr>
                          زمان ورود به مزرعه
                          <p class="card-text">{{ profile.time_into_farm }}</p> <hr>
                          {{  profile.which_farm.active }}
                        {% if profile.which_farm.active %}
                          <a href="{% url 'farms:edit_profilechicken' profile.pk %}" > 
                            <i class="material-icons" style="font-size:60px;color:aqua;">drive_file_rename_outline</i> ویرایش محصول
                          </a>
                        {% endif %}
                        </div>
                      </div>
                </div>
            {% else %}
                <div class="col-12">
                    <h1 class="text-center" style='color:tomato'>هیچگونه داده ای ثبت نگردیده است</h1>
                </div>
            {% endif %}
            </div> <!-- row -->
		</div>		
{% endblock %}

{% block javascript %}

    <script src="{% static 'admin/js/django_jalali.min.js' %}"></script>
{% endblock %}